[package]
name = "shared-nostd"
version = "0.1.0"
edition.workspace = true

[dependencies]
trivalibs_nostd.workspace = true

[target.'cfg(target_arch = "spirv")'.dependencies]
spirv-std.workspace = true
[target.'cfg(not(target_arch = "spirv"))'.dependencies]
glam.workspace = true
