[package]
name = "template_shader"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
spirv-std.workspace = true
trivalibs-nostd.workspace = true
shared-nostd.workspace = true
